# Generated by Django 5.2.7 on 2025-11-29 04:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Driver', 'Driver'), ('Staff', 'Staff')], max_length=20)),
                ('schedule', models.CharField(blank=True, max_length=50)),
                ('wage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('capacity', models.FloatField()),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('vehicle_status', models.CharField(max_length=50)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('fuel_type', models.CharField(max_length=50)),
                ('last_maintenance_date', models.DateField()),
            ],
            options={
                'ordering': ['plate_number'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=50)),
                ('po_schedule_open', models.TimeField()),
                ('po_schedule_close', models.TimeField()),
                ('maximum_storage_capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50)),
                ('license_category', models.CharField(max_length=10)),
                ('license_expiry_date', models.DateField()),
                ('driving_experience_years', models.IntegerField()),
                ('driver_status', models.CharField(max_length=50)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_info', to='PostOffice_App.employee')),
            ],
            options={
                'ordering': ['employee__user__username'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_info', to='PostOffice_App.employee')),
            ],
            options={
                'ordering': ['employee__user__username'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('delivery_status', models.CharField(max_length=50)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_start_time', models.TimeField(blank=True, null=True)),
                ('delivery_end_time', models.TimeField(blank=True, null=True)),
                ('expected_duration', models.DurationField(blank=True, null=True)),
                ('kms_travelled', models.FloatField(default=0)),
                ('driver_notes', models.TextField(blank=True)),
                ('origin_name', models.CharField(max_length=200)),
                ('origin_address', models.CharField(max_length=255)),
                ('origin_contact', models.CharField(blank=True, max_length=50)),
                ('destination_name', models.CharField(max_length=200)),
                ('destination_address', models.CharField(max_length=255)),
                ('destination_contact', models.CharField(blank=True, max_length=50)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='PostOffice_App.employee')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='PostOffice_App.vehicle')),
            ],
            options={
                'ordering': ['delivery_date', 'pk'],
                'unique_together': {('driver', 'vehicle', 'delivery_date')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('driver', 'Driver'), ('staff', 'Staff'), ('manager', 'Manager')], default='client', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id_invoice', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_status', models.CharField(blank=True, max_length=20)),
                ('invoice_type', models.CharField(blank=True, max_length=50)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('invoice_datetime', models.DateTimeField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-invoice_datetime', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_address', models.CharField(max_length=255)),
                ('sender_phone', models.CharField(blank=True, max_length=50)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_address', models.CharField(max_length=255)),
                ('recipient_phone', models.CharField(blank=True, max_length=50)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('item_type', models.CharField(max_length=50)),
                ('weight', models.IntegerField(help_text='Weight in grams', validators=[django.core.validators.MinValueValidator(1)])),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Registered', 'Registered'), ('Ready', 'Ready'), ('Pending', 'Pending'), ('In Transit', 'In Transit'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('in_transition', models.BooleanField(default=False)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver_deliveries', to='PostOffice_App.employee')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='PostOffice_App.invoice')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='PostOffice_App.route')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at', 'tracking_number'],
            },
        ),
    ]
